workflows:
  ios-release:
    name: iOS Build & Publish
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "anga7"
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.onmediawll.ang7"
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        DOTNET_CLI_TELEMETRY_OPTOUT: "1"
        APP_STORE_APPLE_ID: "6738999691"
        BUNDLE_ID: "com.onmediawll.ang7"
        CI: "true"

    scripts:
      - name: Install .NET 9 SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 9.0

      - name: Install iOS MAUI workload only
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install ios maui \
            --skip-manifest-update \
            --source https://api.nuget.org/v3/index.json
          
          $DOTNET workload list
          $DOTNET --info

      - name: Set Info.plist values
        script: |
          PLIST=$CM_BUILD_DIR/Platforms/iOS/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST

      - name: Restore packages for iOS only
        script: |
          $DOTNET restore Ang7.csproj \
            --runtime ios-arm64 \
            --verbosity normal

      - name: Build iOS app
        script: |
          # الحصول على آخر build number
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
          if [ -z $LATEST_BUILD_NUMBER ]; then
            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
            UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          fi
          
          # الحصول على بيانات Code Signing بطريقة مختلفة
          # استخدام المتغيرات المتوفرة في Codemagic
          CERT_NAME=$(keychain list-certificates | jq -r '.[] | select(.common_name | contains("Distribution")) | .common_name' | head -1)
          PROFILE_UUID=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -exec security cms -D -i {} \; | plutil -extract UUID xml1 -o - -- - | xmllint --xpath "//string/text()" - | head -1)
          
          # إذا لم نحصل على الشهادة، استخدم القيم المعروفة
          if [ -z "$CERT_NAME" ]; then
            CERT_NAME="iPhone Distribution: Mohand Ibrahim (ULC59MPPVW)"
          fi
          
          # طباعة المتغيرات للتأكد
          echo "CI Environment: $CI"
          echo "Build Number: $UPDATED_BUILD_NUMBER"
          echo "Certificate: $CERT_NAME"
          echo "Profile UUID: $PROFILE_UUID"
          
          # تنظيف البناء السابق
          $DOTNET clean Ang7.csproj -c Release
          rm -rf obj bin
          
          # بناء ونشر التطبيق في خطوة واحدة لتجنب مشكلة NoBuild
          $DOTNET publish Ang7.csproj \
            --framework net9.0-ios \
            --configuration Release \
            --runtime ios-arm64 \
            --verbosity detailed \
            -p:BuildIpa=True \
            -p:ApplicationDisplayVersion="1.1.6" \
            -p:ApplicationVersion=$UPDATED_BUILD_NUMBER \
            -p:CodesignKey="$CERT_NAME" \
            -p:CodesignProvision="angah_pdf" \
            -p:EnableCodeSigning=true \
            -p:ArchiveOnBuild=true \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:UseInterpreter=false \
            --output ./artifacts

    artifacts:
      - ./artifacts/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: AFTER_APPROVAL
