workflows:
  ios-release:
    name: iOS Build & Publish
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: "anga7"
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.onmediawll.ang7"
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        DOTNET_CLI_TELEMETRY_OPTOUT: "1"
        APP_STORE_APPLE_ID: "6738999691"
        BUNDLE_ID: "com.onmediawll.ang7"

    scripts:
      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH --channel 9.0

      - name: Install MAUI workloads
        script: |
          $DOTNET nuget locals all --clear
          $DOTNET workload install ios maui \
            --source https://api.nuget.org/v3/index.json
          $DOTNET --info

      - name: Set Info.plist values
        script: |
          # تحديد قيم Info.plist تلقائياً
          PLIST=$CM_BUILD_DIR/Platforms/iOS/Info.plist
          PLIST_BUDDY=/usr/libexec/PlistBuddy
          $PLIST_BUDDY -c "Add :ITSAppUsesNonExemptEncryption bool false" $PLIST

      - name: Build iOS app
        script: |
          # الحصول على آخر build number
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
          if [ -z $LATEST_BUILD_NUMBER ]; then
            UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
            UPDATED_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          fi
          
          # الحصول على بيانات Code Signing
          CERT_NAME=$(keychain list-certificates | jq -r '.[] | .common_name')
          PROFILE_NAME=$(find ~/Library/MobileDevice/Provisioning\ Profiles -name "*.mobileprovision" -execdir sh -c '/usr/libexec/PlistBuddy -c "print :Name" /dev/stdin <<< $(security cms -D -i {})' \;)
          
          # طباعة المتغيرات للتأكد
          echo "Build Number: $UPDATED_BUILD_NUMBER"
          echo "Certificate: $CERT_NAME"
          echo "Provisioning Profile: $PROFILE_NAME"
          
          # بناء التطبيق لـ iOS فقط
          $DOTNET publish Ang7.csproj \
            -f net9.0-ios \
            -c Release \
            -r ios-arm64 \
            -p:BuildIpa=True \
            -p:ApplicationDisplayVersion="1.1.6" \
            -p:ApplicationVersion=$UPDATED_BUILD_NUMBER \
            -p:CodesignKey="$CERT_NAME" \
            -p:CodesignProvision="$PROFILE_NAME" \
            -p:EnableCodeSigning=true \
            --self-contained \
            -o ./artifacts

    artifacts:
      - ./artifacts/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - "Internal Testers"
        submit_to_app_store: true
        cancel_previous_submissions: true
        release_type: AFTER_APPROVAL
