workflows:
  ios-release:
    name: iOS Build & Publish
    integrations:
      app_store_connect: "anga7"
    environment:
      groups:
        - ios_code_signing
      vars:
        DOTNET_VERSION: "9.0.100"   # أو "8.0.402" لو 9 مش مستقر معاك
        PROJECT_PATH: "Ang7.csproj"
    scripts:
      - name: Install .NET SDK
        script: |
          brew install --cask dotnet-sdk
          dotnet --version   # تأكد إنه اتسطب
      - name: Install .NET MAUI workloads
        script: |
          dotnet workload install maui
      - name: Restore dependencies
        script: dotnet restore $PROJECT_PATH
      - name: Build iOS
        script: |
          dotnet publish $PROJECT_PATH -f net9.0-ios -c Release \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:PlatformTarget=arm64 \
            -o ./artifacts/ios/
    artifacts:
      - ./artifacts/ios/**/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: true
